name: heroicons_flutter
description: Heroicons from Tailwind Labs as Flutter icons set.
version: 0.2.0
homepage: https://heroicons-flutter.vercel.app

environment:
  sdk: ">=2.18.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  fonts:
    - family: Heroicons Solid
      fonts:
        - asset: assets/fonts/heroicons-solid.ttf
    - family: Heroicons Outline
      fonts:
        - asset: assets/fonts/heroicons-outline.ttf
    - family: Heroicons Mini
      fonts:
        - asset: assets/fonts/heroicons-mini.ttf
